import type { HabitDraft } from "./types";

export const HABIT_TEMPLATES: HabitDraft[] = [
  {
    name: "Morning walk",
    icon: "footprints",
    color: "sage",
    frequency: { kind: "daily" },
    partOfDay: "morning",
    kind: "check",
    target: 1,
    unit: "",
    polarity: "keep",
  },
  {
    name: "Read",
    icon: "book",
    color: "slate",
    frequency: { kind: "daily" },
    partOfDay: "evening",
    kind: "count",
    target: 20,
    unit: "pages",
    polarity: "keep",
  },
  {
    name: "Water",
    icon: "droplets",
    color: "mist",
    frequency: { kind: "daily" },
    partOfDay: "any",
    kind: "count",
    target: 8,
    unit: "glasses",
    polarity: "keep",
  },
  {
    name: "Move",
    icon: "dumbbell",
    color: "clay",
    frequency: { kind: "times", count: 3 },
    partOfDay: "afternoon",
    kind: "check",
    target: 1,
    unit: "",
    polarity: "keep",
  },
  {
    name: "Sit still",
    icon: "focus",
    color: "stone",
    frequency: { kind: "daily" },
    partOfDay: "morning",
    kind: "count",
    target: 10,
    unit: "min",
    polarity: "keep",
  },
  {
    name: "Write",
    icon: "pen",
    color: "ink",
    frequency: { kind: "daily" },
    partOfDay: "morning",
    kind: "check",
    target: 1,
    unit: "",
    polarity: "keep",
  },
  {
    name: "Coffee limit",
    icon: "coffee",
    color: "clay",
    frequency: { kind: "daily" },
    partOfDay: "morning",
    kind: "count",
    target: 2,
    unit: "cups",
    polarity: "avoid",
  },
  {
    name: "No late screens",
    icon: "moon",
    color: "ink",
    frequency: { kind: "daily" },
    partOfDay: "evening",
    kind: "check",
    target: 1,
    unit: "",
    polarity: "avoid",
  },
];
